### ISSUE TITLE
Add license file and do not use Creative Commons

### ISSUE THREAD

**Issue by rugk** [ScottHelme/security-headers-extension#2]
1. Do not use CC licenses should for software: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
2. Please [add the license](https://help.github.com/articles/open-source-licensing/) to this repo.

**Comment by ScottHelme** [comment]
MIT license used and added to repo.

**Comment by rugk** [comment]
Nice. Now you should only change this on [AMO](https://addons.mozilla.org/en-GB/firefox/addon/securityheaders-io-analyser/license/1.0) too.

**Comment by ScottHelme** [comment]
Already have, I assume it takes some time to propagate.
